### ISSUE TITLE
Update package manager to pnpm

### ISSUE THREAD

**Issue by gabrielaraujof** [gabrielaraujof/trick-server#5]
Given the available package managers in the nodejs ecosystem, [pnpm](https://pnpm.io/) seems pretty performant and stills compatible with npm.

Since [Yarn Berry](https://yarnpkg.com/) with PnP is still not very popular mostly because its maturity level at the time, we are going with pnpm right now.

## What is expected

- Install pnpm latest version
- remove `package-lock.json`
- add `pnpm-lock.yaml`

### Pnpm installation

The recommended way is to use corepack:

```shell
$ corepack prepare pnpm@7.2.1 --activate
```

**Comment by vromao** [comment]
Nice!!!
